# Generated by Django 2.1.5 on 2019-01-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact_det', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='songs',
            name='movies',
        ),
        migrations.DeleteModel(
            name='movie',
        ),
        migrations.DeleteModel(
            name='songs',
        ),
    ]
